api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views import UserViewSet, ListingReportViewSet, CommentReportViewSet, ListingViewSet, PlaceViewSet

api_router = DefaultRouter()
api_router.register('users', UserViewSet, 'user')
api_router.register('listingreports', ListingReportViewSet, 'listingreport')
api_router.register('commentreports', CommentReportViewSet, 'commentreport')
api_router.register('listings', ListingViewSet, 'listing')
api_router.register('places', PlaceViewSet, 'place')


urlpatterns = [
    path('', include(api_router.urls)),
    path('admin/', include('rest_framework.urls')),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

listings/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('search/', views.ListingSearchView.as_view(), name='search'),
    path('create/', views.ListingCreateView.as_view(), name='create'),
    path('compare/', views.ListingCompareView.as_view(), name='compare'),
    path('get_json_data/', views.ListingJsonData.as_view(), name='get_json'),

    # Slug related urls
    path('<slug:slug>/', views.ListingDetailView.as_view(), name='detail'),  # Remove the last slash if Django complains
    path('<slug:slug>/update/', views.ListingUpdateView.as_view(), name='update'),
    path('<slug:slug>/delete/', views.ListingDeleteView.as_view(), name='delete'),
    path('<slug:slug>/toggle_status/', views.ListingToggleStatusView.as_view(), name='update_status'),
]

najdistandjango30/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from listings.views import ListingIndexView

from authy.views import LoginView


urlpatterns = [
    path('',            ListingIndexView.as_view(), name='index'),
    path('listings/',   include(('listings.urls', 'listings'), namespace='listings')),
    path('accounts/',   include('registration.backends.default.urls')),  # Used only for the Activation part
    path('user/',       include(('users.urls', 'users'), namespace='accounts')),
    path('auth/',       include(('authy.urls', 'authy'), namespace='authy')),
    path('sp/',         include(('searchprofiles.urls', 'searchprofiles'), namespace='searchprofiles')),
    path('office/',     admin.site.urls),

    # Hack alert, this is needed for the ?next issue when changing the 'auth_login'..
    path('login/',      LoginView.as_view(), name='auth_login'),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
] + urlpatterns
#
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('properties/', views.properties, name='properties'),
    path('bookmarks/', views.bookmarks, name='bookmarks'),
    path('deactivate/', views.deactivate_account, name='deactivate'),
    path('profile/update/', views.update, name='profile_update'),
    path('publisher/<slug:identifier>/', views.publisher, name='publisher'),
]

listings/models.py
from datetime import datetime

from django.core.validators import RegexValidator, MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import F
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

from configdata import REGEX_ZIPCODE_VALIDATOR, HOME_TYPE, INTERIOR_CHOICES, LISTING_TYPE, HEATING_CHOICES
from users.models import BaseModel, User
from users.utils import listing_image_directory_path
from .managers import CustomListingQuerySet


class Place(models.Model):
    """
    A class that represents a place/region
    """
    region = models.CharField(_('Region'), max_length=255)
    city = models.CharField(_('City'), max_length=255)

    def __str__(self):
        return self.city

    def get_region(self):
        return self.region

    class Meta:
        unique_together = ('region', 'city')


class Listing(BaseModel):
    """
    A class that represents a listings. A listings can be a house or an apartment. A listings can be for selling or renting.
    """

    # Listing dependencies
    user = models.ForeignKey('users.User', on_delete=models.CASCADE, related_name='listings')
    city = models.ForeignKey('listings.Place', on_delete=models.SET_NULL, null=True, related_name='listings')

    # Listing specification
    title = models.CharField(_('Title'), max_length=255)
    description = models.TextField(_('Description'))
    address = models.CharField(_('Address'), max_length=80, blank=True)
    zip_code = models.CharField(_('Zip-code'), max_length=10, validators=[
        RegexValidator(regex=REGEX_ZIPCODE_VALIDATOR, message='Zip code must be in format 1234AB', code='invalid_zipcode')])

    # Choices fields
    home_type = models.CharField(_('Type of home'), max_length=10, default='apartment', choices=HOME_TYPE)
    listing_type = models.CharField(_('Listing type'), max_length=10, default='rent', choices=LISTING_TYPE)
    interior = models.CharField(max_length=255, default='unfurnished', choices=INTERIOR_CHOICES)
    heating = models.CharField(max_length=50, choices=HEATING_CHOICES, default='Gas')

    # Numbers fields
    quadrature = models.PositiveSmallIntegerField(_('Quadrature'))
    rooms = models.PositiveSmallIntegerField(_('Rooms'))
    bedrooms = models.PositiveSmallIntegerField(_('Bedrooms'))
    floor = models.PositiveSmallIntegerField(_('Floor'), null=True, blank=True)
    price = models.DecimalField(_('Price in EUR'), max_digits=9, decimal_places=0)
    construction_year = models.IntegerField(_('Construction Year'),
                                            validators=[MinValueValidator(1900), MaxValueValidator(2020)], null=True)

    # Checkbox fields
    basement = models.BooleanField(_('Basement'), default=False)
    parking = models.BooleanField(_('Parking place'), default=False)
    elevator = models.BooleanField(_('Elevator'), default=False)
    balcony = models.BooleanField(_('Balcony'), default=False)

    # Listing admin data
    is_approved = models.NullBooleanField(_('Approved?'), default=None)
    is_available = models.BooleanField(_('Available?'), default=True)
    rejection_reason = models.CharField(_('Rejection reason'), max_length=255, null=True, blank=True)
    available_from = models.DateField(blank=True, null=True)
    rental_period = models.PositiveSmallIntegerField(_('Minimum rental period (in months)'), default=6, blank=True, null=True)
    times_visited = models.PositiveIntegerField(_('Times visited'), default=0)
    soft_deleted = models.BooleanField(_('Soft deleted'), default=False)
    slug = models.SlugField(max_length=255, unique=True)

    objects = CustomListingQuerySet.as_manager()

    class Meta:
        ordering = ['-created_at', ]

    def __str__(self):
        return self.slug

    def get_images(self):
        return self.images.all()

    def get_cover_image(self):
        if self.get_images():
            return self.images.first().image

    def get_images_count(self):
        return int(self.images.all().count())

    def get_absolute_url(self):
        return reverse('listings:detail', kwargs={'slug': self.slug})

    def get_bookmarked_by(self):
        return self.bookmarked_by.all()

    def is_active(self):
        return self.is_available and self.is_approved

    def toggle_status(self):
        self.is_available = not self.is_available
        self.save()

    def save(self, *args, **kwargs):
        if not self.id:
            # Let's create unique slug for the article
            date_time_object = datetime.utcnow().strftime("%d%m%Y%H%M%S")
            self.slug = "-".join([slugify(self.title), date_time_object])
        super().save(*args, **kwargs)

    # This ensures that all related images are deleted from the system
    def delete(self, using=None, keep_parents=False):
        for image in self.images.all():
            image.delete()
            image.image.storage.delete(image.image.name)
        super().delete()


class Image(BaseModel):
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=listing_image_directory_path)
    order = models.PositiveSmallIntegerField(default=1, blank=True, null=True)

    def __str__(self):
        return self.image.name


class Saved(models.Model):
    """
    A class used for saving listings for later
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='saved')
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='saved')

    def __str__(self):
        return f"{self.user} - {self.listing}"


class Comment(BaseModel):
    """
    A class that represent listings's comments
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField(_('Comment body'))

    def __str__(self):
        return f"{self.body}"

listings/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Listing

help_texts = [
    _('Make sure you pick a meaningful title that will best describe your property. Title can NOT be updated later!'),
    _('Property title can NOT be updated.'),
    _('Add any images that you think might spark an interest in your potential buyers! Allowed formats: .JPG, .JPEG, .PNG.'),
    _('If property is for sell - type overall selling price. <br/> If property is for rent - type monthly rent cost.')
]


class ListingCreateForm(forms.ModelForm):
    title = forms.CharField(label='Property title', help_text=help_texts[0])
    images = forms.ImageField(widget=forms.ClearableFileInput(attrs={'multiple': True}), help_text=help_texts[2])
    price = forms.DecimalField(help_text=help_texts[3])

    class Meta:
        model = Listing
        exclude = ('user', 'slug', 'address', 'times_visited', 'soft_deleted', 'is_approved',
                   'is_available', 'rejection_reason', 'available_from', 'rental_period')
        widgets = {
            'description': forms.Textarea(attrs={'rows': 2, "cols": 15})
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) < 10:
            raise forms.ValidationError("Add brief summary with at least 10 characters!")
        return title

    def clean_description(self):
        description = self.cleaned_data['description']
        if len(description) < 15:
            raise forms.ValidationError("Add description for the property with at least 15 characters!")
        return description

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].empty_label = None


class ListingUpdateForm(ListingCreateForm):
    title = forms.CharField(label='Property title', help_text=help_texts[1], disabled=True)
    images = forms.ImageField(required=False, widget=forms.ClearableFileInput(attrs={'multiple': True}), help_text=help_texts[2])

templates/listings/list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load widget_tweaks %}

{% block title %}
    {% include 'includes/title.html' %}
{% endblock %}

{% block content %}

<!-- Banner
================================================== -->
<div class="parallax" 
data-background="{% static 'assets/images/home-parallax.jpg' %}" 
data-color="#36383e" 
data-color-opacity="0.45" 
data-img-width="2500" 
data-img-height="1600">
	<div class="parallax-content">

		<div class="container">
			<div class="row">
				<div class="col-md-12">

					<!-- Main Search Container -->
					<div class="main-search-container">
						<h2>Find Your Dream Home</h2>

						<!-- Main Search -->
						<form class="main-search-form" action="{% url 'listings:search' %}" method="get" autocomplete="off">
                            <!-- Type -->
							<div class="search-type">
								<label class="active"><input class="first-tab" name="tab" checked="checked" type="radio">Any Status</label>
								<label><input name="tab" type="radio">For Sale</label>
								<label><input name="tab" type="radio">For Rent</label>
								<div class="search-type-arrow"></div>
                            </div>

                            <!-- Box -->
							<div class="main-search-box">

                                {{ filter.form.non_field_errors }}
                                <div class="main-search-input larger-input">
                                    {{ filter.form.title.errors }}
                                    {{ filter.form.title.label_tag }}
                                    {{ filter.form.title }}
                                    <button class="button" type="submit">Search</button>
                                </div>
                                <div class="row with-forms">
                                    <div class="col-md-4">
                                        {{ filter.form.city.errors }}
										{{ filter.form.city.label_tag }}
										{% render_field filter.form.city class="chosen-select-no-single" %}
                                    </div>
                                    <div class="col-md-8 search-by-price">
                                        {{ filter.form.price.errors }}
                                        {{ filter.form.price.label_tag }}
                                        {{ filter.form.price }}
                                    </div>
                                </div>

                            </div>
                        </form>

					</div>
					<!-- Main Search Container / End -->

				</div>
			</div>
		</div>

	</div>
</div>

<!-- Content
================================================== -->
<div class="container margin-bottom-100">
	<div class="row">
	
		<div class="col-md-12">
			<h3 class="headline margin-bottom-25 margin-top-65">Featured Properties</h3>
		</div>

		<!-- Carousel -->
		<div class="col-md-12">
			<div class="carousel">
                {% for listing in latest_5 %}
                    {% include 'includes/listings/vertical_card.html' %}
                {% endfor %}
			</div>
		</div>
		<!-- Carousel / End -->

	</div>
</div>

<!-- Flip banner -->
<a href="listings-half-map-grid-standard.html"
class="flip-banner parallax"
data-color="#6449E7"
data-color-opacity="0.9">
	<div class="flip-banner-content">
		<h2 class="flip-visible">We help people and homes find each other</h2>
		<h2 class="flip-hidden">Browse Properties <i class="sl sl-icon-arrow-right"></i></h2>
	</div>
</a>
<!-- Flip banner / End -->

{% endblock %}

templates/listings/pagination.html
{% load custom_paginator_tag %}

{% if is_paginated %}
    {% if page_obj.has_previous %}
        <a href="?{% param_replace page=1 %}">First</a>
        {% if page_obj.previous_page_number != 1 %}
            <a href="?{% param_replace page=page_obj.previous_page_number %}">Previous</a>
        {% endif %}
    {% endif %}

    Page {{ page_obj.number }} of {{ paginator.num_pages }}

    {% if page_obj.has_next %}
        {% if page_obj.next_page_number != paginator.num_pages %}
            <a href="?{% param_replace page=page_obj.next_page_number %}">Next</a>
        {% endif %}
            <a href="?{% param_replace page=paginator.num_pages %}">Last</a>
    {% endif %}
{% endif %}
<p>Total objects: {{ paginator.count }}</p>

templates/listings/update.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    {% include '_shared/title.html' %}
{% endblock %}

{% block content %}

{% include '_shared/breadcrumbs.html' %}

<div class="container padding-bottom-70">
    <div class="row">
        <!-- Sidebar widget -->
		<div class="col-md-4">
			<div class="sidebar left">
				{% include '_shared/profile-sidemenu.html' %}
			</div>
        </div>



        <!-- Submit Page -->
        <div class="col-md-8 padding-bottom-70">
            <div class="main-content">
                <div class="update-header">
                    <a class="back-to-listings" href="{% if prev_page %}{{ prev_page }}{% else %}#{% endif %}"></a>
                    <h2>Update your property</h2>
                </div>
                <i>Note: At this moment, you can only add new images, but can not delete existing. We are working on it.</i><br/><br/>
    
                <form method="post" enctype="multipart/form-data" autocomplete="off">
                    {% csrf_token %}
    
                    <div class="submit-page">
    
                        <!-- Section -->
                        <h3>Basic Information</h3>
                        <div class="submit-section">
    
                            <!-- Title -->
                            <div class="form">
                                <label for="id_title">{{ form.title.label }}
                                    <i class="tip"
                                       data-tip-content="{{ form.title.help_text }}">
                                    </i>
                                </label>
                                {{ form.title }}
    
                            </div>
    
                            <!-- Row -->
                            <div class="row with-forms">
    
                                <!-- Status -->
                                <div class="col-md-4">
                                    {{ form.listing_type.label_tag }}
                                    {% render_field form.listing_type class="chosen-select-no-single" %}
                                    {{ form.listing_type.errors }}
                                    <small class="help-text text-muted">{{ form.listing_type.help_text }}</small>
                                </div>
    
                                <!-- Type -->
                                <div class="col-md-4">
                                    {{ form.home_type.label_tag }}
                                    {% render_field form.home_type class="chosen-select-no-single" %}
                                    {{ form.home_type.errors }}
                                    <small class="help-text text-muted">{{ form.home_type.help_text }}</small>
                                </div>
    
                               <!-- Interior -->
                                <div class="col-md-4">
                                    {{ form.interior.label_tag }}
                                    {% render_field form.interior class="chosen-select-no-single" %}
                                    {{ form.interior.errors }}
                                    <small class="help-text text-muted">{{ form.interior.help_text }}</small>
                                </div>
    
                            </div>
                            <!-- Row / End -->
    
                             <div class="row with-forms">
    
                                <!-- Price -->
                                <div class="col-md-4">
                                    <label for="{{form.price.id_for_label}}">{{ form.price.label }} <i class="tip"
                                       data-tip-content="{{ form.price.help_text }}"></i></label>
                                    <div class="select-input disabled-first-option">
                                        <input type="hidden" data-unit="&euro;">
                                        {{ form.price }}
                                    </div>
                                    {{ form.price.errors }}
                                </div>
    
                                <!-- Area -->
                                <div class="col-md-4">
                                    <label for="{{form.quadrature.id_for_label}}">Total Area</label>
                                    <div class="select-input disabled-first-option">
                                        <input type="hidden" data-unit="m2">
                                        {{ form.quadrature }}
                                    </div>
                                    {{ form.quadrature.errors }}
                                    <small class="help-text text-muted">{{ form.quadrature.help_text }}</small>
                                </div>
    
                                <!-- Construction Year -->
                                <div class="col-md-4">
                                    <label for="{{form.construction_year.id_for_label}}">Construction Year</label>
                                    {{ form.construction_year }}
                                    {{ form.construction_year.errors }}
                                    <small class="help-text text-muted">{{ form.construction_year.help_text }}</small>
                                </div>
                            </div>
    
    
                        </div>
                        <!-- Section End -->
    
                        <!-- Section -->
                        <h3>Gallery</h3>
                        <div class="submit-section">
                            <input type="file" value="images" name="images" multiple>
                            <small class="help-text text-muted">{{ form.images.help_text }}</small>
                        </div>
    {#                    <div class="submit-section">#}
    {#                        <div action="/listings/proba/" id="propertyUploadImages" class="dropzone" method="post" enctype="multipart/form-data">#}
    {#                                    <input id="imageHolder" type="file" name="images" multiple required >#}
    {#                            {% csrf_token %}#}
    {#                            <div class="fallback">#}
    {#                                <input type="file" name="images" multiple required >#}
    {#                            </div>#}
    {#                            <!-- <button class="button fullwidth margin-top-5" id="" type="submit">Submit</button> -->#}
    {#                        </div>#}
    {#                    </div>#}
                        <!-- Section End -->
    
                        <!-- Section -->
                        <h3>Location</h3>
                        <div class="submit-section">
    
                            <!-- Row -->
                            <div class="row with-forms">
                                <!-- City -->
                                <div class="col-md-6">
                                    {{ form.city.label_tag }}
                                    {% render_field form.city class="chosen-select-no-single" %}
                                    {{ form.city.errors }}
                                    <small class="help-text text-muted">{{ form.city.help_text }}</small>
                                </div>
    
                                <!-- Zip-Code -->
                                <div class="col-md-6">
                                    {{ form.zip_code.label_tag }}
                                    {{ form.zip_code }}
                                    {{ form.zip_code.errors }}
                                    <small class="help-text text-muted">{{ form.zip_code.help_text }}</small>
                                </div>
    
                             </div>
                            <!-- Row / End -->
    
                        </div>
                        <!-- Section End -->
    
                        <!-- Section -->
                        <h3>Detailed Information</h3>
                        <div class="submit-section">
    
                            <!-- Description -->
                            <div class="form">
                                <label for="id_description">Description</label>
                                {{ form.description }}
                                {{ form.description.errors }}
                            </div>
    
                            <!-- Row -->
                            <div class="row with-forms">
                                <!-- Heating -->
                                <div class="col-md-3">
                                    <label for="{{form.heating.id_for_label}}">Heating</label>
                                    {% render_field form.heating class="chosen-select-no-single" %}
                                    {{ form.heating.errors }}
                                    <small class="help-text text-muted">{{ form.heating.help_text }}</small>
                                </div>
    
                                <!-- Rooms -->
                                <div class="col-md-3">
                                    <label for="{{form.rooms.id_for_label}}">No. of Rooms</label>
                                    {{ form.rooms }}
                                    {{ form.rooms.errors }}
                                    <small class="help-text text-muted">{{ form.construction_year.help_text }}</small>
                                </div>
    
                                <!-- Bedrooms -->
                                <div class="col-md-3">
                                    <label for="{{form.bedrooms.id_for_label}}">No. of Bedrooms</label>
                                    {{ form.bedrooms }}
                                    {{ form.bedrooms.errors }}
                                    <small class="help-text text-muted">{{ form.bedrooms.help_text }}</small>
                                </div>
    
                                  <!-- Floor -->
                                <div class="col-md-3">
                                    <label for="{{form.floor.id_for_label}}">Floor <span>(optional)</span></label>
                                    {{ form.floor }}
                                    {{ form.floor.errors }}
                                    <small class="help-text text-muted">{{ form.floor.help_text }}</small>
                                </div>
    
                            </div>
                            <!-- Row / End -->
    
    
                            <!-- Checkboxes -->
                            <h5 class="margin-top-30">Other Features <span>(optional)</span></h5>
                            <div class="checkboxes in-row margin-bottom-20">
    
                                <input id="check-2" type="checkbox" name="basement" {% if listing.basement %}checked {% endif %}>
                                <label for="check-2">Basement</label>
    
                                <input id="check-5" type="checkbox" name="parking" {% if listing.parking %}checked {% endif %}>
                                <label for="check-5">Parking</label>
    
                                <input id="check-6" type="checkbox" name="elevator" {% if listing.elevator %}checked {% endif %}>
                                <label for="check-6">Elevator</label>
    
                                <input id="check-7" type="checkbox" name="balcony" {% if listing.balcony %}checked {% endif %}>
                                <label for="check-7">Balcony</label>
    
                            </div>
                            <!-- Checkboxes / End -->
    
                        </div>
                        <!-- Section / End -->
    
                    </div>
                    <button type="submit" class="button">Submit</button>
                </form>
            </div>
        </div>

    </div>
</div>

{% endblock %}