api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views import UserViewSet, ListingReportViewSet, CommentReportViewSet, ListingViewSet, PlaceViewSet

api_router = DefaultRouter()
api_router.register('users', UserViewSet, 'user')
api_router.register('listingreports', ListingReportViewSet, 'listingreport')
api_router.register('commentreports', CommentReportViewSet, 'commentreport')
api_router.register('listings', ListingViewSet, 'listing')
api_router.register('places', PlaceViewSet, 'place')


urlpatterns = [
    path('', include(api_router.urls)),
    path('admin/', include('rest_framework.urls')),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

najdistandjango30/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from listings.views import ListingIndexView

from authy.views import LoginView


urlpatterns = [
    path('',            ListingIndexView.as_view(), name='index'),
    path('listings/',   include(('listings.urls', 'listings'), namespace='listings')),
    path('accounts/',   include('registration.backends.default.urls')),  # Used only for the Activation part
    path('user/',       include(('users.urls', 'users'), namespace='accounts')),
    path('auth/',       include(('authy.urls', 'authy'), namespace='authy')),
    path('sp/',         include(('searchprofiles.urls', 'searchprofiles'), namespace='searchprofiles')),
    path('office/',     admin.site.urls),

    # Hack alert, this is needed for the ?next issue when changing the 'auth_login'..
    path('login/',      LoginView.as_view(), name='auth_login'),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
] + urlpatterns
#
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

searchprofiles/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('manage/',             views.search_profile_manage,    name='manage'),
    path('create/',             views.search_profile_create,    name='create'),
    path('toggle/',             views.search_profile_toggle,    name='toggle'),
    path('update/<int:pk>/',    views.search_profile_update,    name='update'),
    path('delete/<int:pk>/',    views.search_profile_delete,    name='delete'),
]

searchprofiles/models.py
from django.db import models

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from users.models import BaseModel, User
from .managers import CustomSearchProfileQueryset


class SearchProfiles(BaseModel):
    """
    A class used for saving user Search Profiles.
    Will be used for informing a user when a listings is in his listings criteria
    """
    user = models.ForeignKey("users.User", on_delete=models.CASCADE, related_name='searchprofiles')
    title = models.CharField(max_length=255, null=True)
    city = models.ForeignKey("listings.Place", on_delete=models.DO_NOTHING)
    is_active = models.BooleanField(default=True)

    # Number fields
    rooms = models.PositiveSmallIntegerField(_("Number of rooms"), null=True, blank=True)
    bedrooms = models.PositiveSmallIntegerField(_("Number of bedrooms"), null=True, blank=True)
    min_price = models.DecimalField(_("Minimum price"), max_digits=9, decimal_places=0)
    max_price = models.DecimalField(_("Maximum price"),  max_digits=9, decimal_places=0)

    # Choices fields
    home_type = models.CharField(_('Home type'), max_length=50, null=True, blank=True)
    listing_type = models.CharField(_('Listing type'), max_length=5, null=True, blank=True)
    interior = models.CharField(_('Interior'), max_length=50, null=True, blank=True)
    frequency = models.CharField(_("Update frequency"), max_length=50)

    objects = CustomSearchProfileQueryset.as_manager()

    class Meta:
        unique_together = ('user', 'title')
        verbose_name_plural = 'Search profiles'

    def __str__(self):
        return self.title

    def clean(self):
        if self.rooms and self.bedrooms and self.rooms < self.bedrooms:
            raise ValidationError({'rooms': "You can not have less rooms than bedrooms"})
        if self.min_price and self.max_price and self.min_price > self.max_price:
            raise ValidationError({'min_price': "Minimum price can't be bigger than maximum price"})

    def get_specs_html(self):
        return """
        Range: {}-{} €<br/>
        City: {} <br/>
        Listing type: {} <br/>
        Home type: {} <br/>
        Interior: {} <br/>
        Rooms: {} <br/>
        Bedrooms: {}
        """.format(self.min_price, self.max_price, self.city,
                   self.listing_type.title(),
                   # These are optional, hence the check for value
                   self.home_type.title() if self.home_type else '',
                   self.interior.title() if self.interior else '',
                   self.rooms if self.rooms else '',
                   self.bedrooms if self.bedrooms else '',)

searchprofiles/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .form_widgets import SelectWidgetWithDisabledOption
from .models import SearchProfiles
from configdata import UPDATE_FREQUENCIES, HOME_TYPE, INTERIOR_CHOICES

_premium_fields = ['interior', 'home_type', 'rooms', 'bedrooms']


class UserSearchProfileForm(forms.ModelForm):
    title = forms.CharField(label='Name your Search Profile', help_text='A unique title that will mean something to you', max_length=255, )
    frequency = forms.ChoiceField(required=True, widget=SelectWidgetWithDisabledOption, choices=UPDATE_FREQUENCIES,
                                 help_text='How often to receive notifications about new properties', initial='biweekly')

    class Meta:
        model = SearchProfiles
        exclude = ('user', 'is_active')

        # To comply with the Index page Min-Max slider
        widgets = {
            'min_price': forms.NumberInput(attrs={'id': 'id_price_0'}),
            'max_price': forms.NumberInput(attrs={'id': 'id_price_1'}),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.is_updating = kwargs.pop('update', None)
        super().__init__(*args, **kwargs)
        self.fields['city'].empty_label = None
        self.fields['home_type'] = forms.ChoiceField(choices=HOME_TYPE, required=False)
        self.fields['interior'] = forms.ChoiceField(choices=INTERIOR_CHOICES, required=False)
        self.fields['listing_type'] = forms.ChoiceField(choices=[('rent', 'To rent'), ('buy', 'To buy')])
        # TODO: Might need to change 'buy' to 'sell' for easier DB query

        if not self.user.is_premium_user:
            self.fields['frequency'].widget.disabled_choices = ['instant',]
            for field in _premium_fields:
                self.fields[field].widget.attrs['disabled'] = 'disabled'
                self.fields[field].required = False

            if not self.is_updating and self.user.has_reached_max_number_of_sp():
                for key, value in self.fields.items():
                    value.disabled = True

    def clean_title(self):
        title = self.cleaned_data['title']
        exists = SearchProfiles.objects.exclude(pk=self.instance.pk).filter(user=self.user, title__iexact=title).exists()
        if exists:
            raise forms.ValidationError(_('You already have a Search Profile with this exact Title.'))
        return title

    def clean(self):
        cleaned_data = super().clean()

        # Make sure the non-Premium user does not tamper the form manually,
        # by enabling a Premium field-only and add value to it
        if not self.user.is_premium_user:
            if cleaned_data['frequency'] == 'instant':
                self.add_error('frequency', "This is a Premium feature!")
            for field in _premium_fields:
                if cleaned_data[field]:
                    self.add_error(field, "This is a Premium feature!")
        return cleaned_data

searchprofiles/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods

from configdata import FORBIDDEN_MESAGE
from listings.decorators import ajax_required
from .forms import UserSearchProfileForm
from .models import SearchProfiles


@login_required()
def search_profile_manage(request):
    context = {'title': "Manage Search Profiles"}
    context.update({'reached_max_sp': request.user.has_reached_max_number_of_sp(),
                    'search_profiles': request.user.get_search_profiles(),
                    'active_sp': request.user.get_search_profiles().count_active(),
                    'crumbs': {
                        "Home": reverse('index'),
                        "Account": reverse('accounts:profile'),
                        "Search Profile": '#',
                    }
                    })
    return render(request, 'searchprofile/manage.html', context)


@login_required()
def search_profile_create(request):
    context = {
        'title': "Create Search Profile",
        'crumbs': {
           "Home": reverse('index'),
           "Account": reverse('accounts:profile'),
           "Search Profile": reverse('searchprofiles:manage'),
           "Create": "#"
        }
    }

    if request.method == 'POST':
        form = UserSearchProfileForm(request.POST, user=request.user)
        context.update({'form': form})
        if form.is_valid():
            sp = form.save(commit=False)
            sp.user = request.user
            sp.save()
            messages.success(request, _("Search Profile added!"))
            return redirect(reverse('searchprofiles:manage'))
        else:
            return render(request, 'searchprofile/create.html', context)

    form = UserSearchProfileForm(user=request.user)

    context.update({'form': form, 'reached_max_sp': request.user.has_reached_max_number_of_sp()})
    return render(request, 'searchprofile/create.html', context)


@login_required()
def search_profile_delete(request, pk):
    search_profile = get_object_or_404(SearchProfiles, pk=pk)
    if search_profile.user != request.user:
        return HttpResponseForbidden(_(FORBIDDEN_MESAGE))
    search_profile.delete()
    messages.info(request, _("Search Profile deleted."))
    return redirect(reverse('searchprofiles:manage'))


@login_required()
def search_profile_update(request, pk):
    search_profile = get_object_or_404(SearchProfiles, pk=pk)
    if search_profile.user != request.user:
        return HttpResponseForbidden(_(FORBIDDEN_MESAGE))

    context = {
        'title': _('Update Search Profile'),
        'crumbs': {
            "Home": reverse('index'),
            "Account": reverse('accounts:profile'),
            "Search Profile": reverse('searchprofiles:manage'),
            "Update": "#"
        }
    }

    if request.method == 'POST':
        form = UserSearchProfileForm(request.POST, instance=search_profile, user=request.user, update=True)
        context.update({'form': form})
        if form.is_valid():
            if form.has_changed():
                form.save()
                messages.info(request, _("Search Profile updated!"))
            return redirect(reverse('searchprofiles:manage'))
        else:
            return render(request, 'searchprofile/update.html', context)

    form = UserSearchProfileForm(user=request.user, instance=search_profile, update=True)
    context.update({'form': form})
    return render(request, 'searchprofile/update.html', context)


@ajax_required
@require_http_methods(['POST'])
@csrf_exempt
def search_profile_toggle(request):
    # Sanity checks
    ajax_user = getattr(request, 'user', None)
    if ajax_user.is_anonymous:
        return JsonResponse({'error': 'You need to be logged-in for this action'}, status=403)
    sp_key = request.POST.get('sp_pk', None)
    if not sp_key:
        return JsonResponse({'error': 'Requested key not found in POST.'}, status=403)
    try:
        search_profile = SearchProfiles.objects.get(pk=sp_key)
    except SearchProfiles.DoesNotExist:
        return JsonResponse({'error': 'Requested Search Profile not found.'}, status=404)
    if search_profile.user != ajax_user:
        return JsonResponse({'error': "You don't have permission to do this action."}, status=403)

    search_profile.is_active = not search_profile.is_active
    search_profile.save()
    return JsonResponse({'data': 'Search Profile successfully updated!'}, status=200)

templates/searchprofile/create.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    {% include '_shared/title.html' %}
{% endblock %}

{% block content %}
    {% include '_shared/breadcrumbs.html' %}

    <div class="container padding-bottom-70">
        <div class="row">

             <!-- Sidebar widget -->
            <div class="col-md-4">
                <div class="sidebar left">
                    {% include '_shared/profile-sidemenu.html' %}
                </div>
            </div>

            <!-- Manage Page -->
            <div class="col-md-8 padding-bottom-70">
                <div class="main-content">
                    {% if reached_max_sp %}
                        <p style="color: red;">You've reached the maximum number of Search profiles you can have.<br>
                            <a href="#">Upgrade to Premium</a> to have access to more Search profiles and many other cool features.</p>
                    {% endif %}
                    <form method="post" autocomplete="off">
                        {% csrf_token %}
                        {% for hidden_field in form.hidden_fields %}
                            {{ hidden_field }}
                        {% endfor %}
    
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">
                            {% for error in form.non_field_errors %}
                                {{ error }}
                            {% endfor %}
                            </div>
                        {% endif %}
    
                        <div class="submit-page">
    
                            <div class="form">
                                {{ form.title.label_tag }}
                                {{ form.title }}
                                {{ form.title.errors }}
                                <small class="help-text text-muted">{{ form.title.help_text }}</small>
                            </div>
    
                            <!-- Price Range -->
                            <div class="form">
                                <div class="range-slider">
                                    <label for="{{ form.price.id_for_label }}">Price Range</label>
                                    <div class="price-range" data-min="0" data-max="400000" data-unit="&euro;">
                                        <input type='text' class='first-slider-value' disabled/>
                                        <input type='text' class='second-slider-value' disabled/>
                                        <div class="range-slider-values">
                                            {{ form.min_price.label_tag}}
                                            {{ form.min_price }}
    
                                            {{ form.max_price.label_tag}}
                                            {{ form.max_price }}
                                        </div>
                                    </div>
                                    <small class="help-text text-muted">{{ form.price.help_text }}</small>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
    
                            <!-- Frequency -->
                            <div class="form row with-forms">
                                <div class="col-md-4">
                                    {{ form.frequency.label_tag }}
                                    {% render_field form.frequency class="chosen-select-no-single" %}
                                    {{ form.frequency.errors }}
                                    <small class="help-text text-muted">{{ form.frequency.help_text }}</small>
                                </div>
    
                                <!-- City -->
                                <div class="col-md-4">
                                    {{ form.city.label_tag }}
                                    {% render_field form.city class="chosen-select-no-single" %}
                                    {{ form.city.errors }}
                                    <small class="help-text text-muted">{{ form.city.help_text }}</small>
                                </div>
    
                                <!-- Listing Type -->
                                <div class="col-md-4">
                                    {{ form.listing_type.label_tag }}
                                    {% render_field form.listing_type class="chosen-select-no-single" %}
                                    {{ form.listing_type.errors }}
                                    <small class="help-text text-muted">{{ form.listing_type.help_text }}</small>
                                </div>
                            </div>
    
                            <br/>
                            <h4>Premium fields (Optional):</h4>
                            <hr/>
    
                            {% if not user.is_premium_user %}
                                <p style="color: red;">Upgrade to <a href="#">Premium</a> to access these features. </p>
                            {% endif %}
    
                            <div class="form row with-forms">
                                <!-- Home Type -->
                                <div class="col-md-6">
                                    {{ form.home_type.label_tag }}
                                    {% render_field form.home_type class="chosen-select-no-single" %}
                                    {{ form.home_type.errors }}
                                    <small class="help-text text-muted">{{ form.home_type.help_text }}</small>
                                </div>
    
                                <!-- Interior -->
                                <div class="col-md-6">
                                    {{ form.interior.label_tag }}
                                    {% render_field form.interior class="chosen-select-no-single" %}
                                    {{ form.interior.errors }}
                                    <small class="help-text text-muted">{{ form.interior.help_text }}</small>
                                </div>
                            </div>
    
                            <div class="form row with-forms">
                                <!-- Rooms -->
                                <div class="col-md-6">
                                    {{ form.rooms.label_tag }}
                                    {{ form.rooms }}
                                    {{ form.rooms.errors }}
                                    <small class="help-text text-muted">{{ form.rooms.help_text }}</small>
                                </div>
    
                                <!-- Bedrooms -->
                                <div class="col-md-6">
                                    {{ form.bedrooms.label_tag }}
                                    {{ form.bedrooms }}
                                    {{ form.bedrooms.errors }}
                                    <small class="help-text text-muted">{{ form.bedrooms.help_text }}</small>
                                </div>
                            </div>
                        </div>
    
                        <p><i>More options to be added soon!</i></p>
    
                        <button class="button margin-top-10" type="submit" {% if reached_max_sp %} disabled {% endif %}>Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/searchprofile/manage.html
{% extends 'base.html' %}

{% block title %}
    {% include '_shared/title.html' %}
{% endblock %}

{% block content %}
    {% include '_shared/breadcrumbs.html' %}

    <div class="container padding-bottom-70">
        <div class="row">

             <!-- Sidebar widget -->
            <div class="col-md-4">
                <div class="sidebar left">
                    {% include '_shared/profile-sidemenu.html' %}
                </div>
            </div>

            <!-- Manage Page -->
            <div class="col-md-8 padding-bottom-70">
                <div class="main-content">
                    {% if reached_max_sp %}
                            <p style="color: red;">You've reached the maximum number of Search profiles you can have.<br>
                               <a href="#">Upgrade to Premium</a> to have access to more Search profiles and many other cool features.</p>
                    {% endif %}
                    <p>"Search Profile" is a functionality that notifies you via e-mail when a new property has been listed
                    on our website that matches your criteria. <br/>
                    The notification interval is set in the Search Profile itself. <br/>
                    "Instant" notifications are only available for <a href="#">Premium</a> users.
                    </p>
    
                    <table class="basic-table responsive-table padding-top-20 search-profile">
                        <tr>
                            <th>Title</th>
                            <th>Frequency</th>
                            <th>Specs</th>
                            <th>Status</th>
                            <th><i class="fa fa-file-text"></i> Actions</th>
                        </tr>
                        {% if search_profiles %}
                            {% for sp in search_profiles %}
                                <tr>
                                    <td><a href="javascript:;" class="tooltip top" title="{{ sp.title }}">{{ sp.title|truncatewords:"4" }}</a></td>
                                    <td>{{ sp.frequency.title }}</td>
                                    <td><a href="javascript:;" class="tooltip top" title="{{ sp.get_specs_html }}">More info...</a></td>
    
                                    <td>
                                        <div class="input-wrapper">
                                            <div class="input-checkbox-switch">
                                                <input type="checkbox" name="{{ sp.pk }}" id="spSwitch{{ sp.pk }}" value="{{ sp.is_active }}" {% if sp.is_active %}checked {% endif %} />
                                                <label for="spSwitch{{ sp.pk }}"></label>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="action">
                                        <a href="{% url 'searchprofiles:update' sp.pk %}"><i class="fa fa-pencil"></i> Update</a> <br/>
                                        <a href="{% url 'searchprofiles:delete' sp.pk %}" class="delete" onclick="return confirm('Are you sure you want to delete this listing?');">
                                            <i class="fa fa-remove"></i> Delete</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <p>You don't have any Search Profiles. Would you like to <a href="{% url 'searchprofiles:create' %}">create one?</a></p>
                        {% endif %}
                    </table>
                    <p class="margin-top-20"><i>Total Search profiles: {{ search_profiles|length }}, out of which {{ active_sp }} are active.</i></p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/searchprofile/update.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    {% include '_shared/title.html' %}
{% endblock %}

{% block content %}
    {% include '_shared/breadcrumbs.html' %}

    <div class="container padding-bottom-70">
        <div class="row">

             <!-- Sidebar widget -->
            <div class="col-md-4">
                <div class="sidebar left">
                    {% include '_shared/profile-sidemenu.html' %}
                </div>
            </div>

            <div class="col-md-8 padding-bottom-70">
                <div class="main-content">
                    <form method="post" autocomplete="off">
                        {% csrf_token %}
                        {% for hidden_field in form.hidden_fields %}
                            {{ hidden_field }}
                        {% endfor %}
    
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">
                            {% for error in form.non_field_errors %}
                                {{ error }}
                            {% endfor %}
                            </div>
                        {% endif %}
    
                        <div class="submit-page">
    
                            <div class="form">
                                {{ form.title.label_tag }}
                                {{ form.title }}
                                {{ form.title.errors }}
                                <small class="help-text text-muted">{{ form.title.help_text }}</small>
                            </div>
    
                            <!-- Price Range -->
                            <div class="form">
                                <div class="range-slider">
                                    <label for="{{ form.price.id_for_label }}">Price Range</label>
                                    <div class="price-range" data-min="0" data-max="400000" data-unit="&euro;">
                                        <input type='text' class='first-slider-value' disabled/>
                                        <input type='text' class='second-slider-value' disabled/>
                                        <div class="range-slider-values">
                                            {{ form.min_price.label_tag}}
                                            {{ form.min_price }}
    
                                            {{ form.max_price.label_tag}}
                                            {{ form.max_price }}
                                        </div>
                                    </div>
                                    <small class="help-text text-muted">{{ form.price.help_text }}</small>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
    
                            <!-- Frequency -->
                            <div class="form row with-forms">
                                <div class="col-md-4">
                                    {{ form.frequency.label_tag }}
                                    {% render_field form.frequency class="chosen-select-no-single" %}
                                    {{ form.frequency.errors }}
                                    <small class="help-text text-muted">{{ form.frequency.help_text }}</small>
                                </div>
    
                                <!-- City -->
                                <div class="col-md-4">
                                    {{ form.city.label_tag }}
                                    {% render_field form.city class="chosen-select-no-single" %}
                                    {{ form.city.errors }}
                                    <small class="help-text text-muted">{{ form.city.help_text }}</small>
                                </div>
    
                                <!-- Listing Type -->
                                <div class="col-md-4">
                                    {{ form.listing_type.label_tag }}
                                    {% render_field form.listing_type class="chosen-select-no-single" %}
                                    {{ form.listing_type.errors }}
                                    <small class="help-text text-muted">{{ form.listing_type.help_text }}</small>
                                </div>
                            </div>
    
                            <br/>
                            <h4>Premium fields (Optional):</h4>
                            <hr/>
    
                            {% if not user.is_premium_user %}
                                <p style="color: red;">Upgrade to <a href="#">Premium</a> to access these features. </p>
                            {% endif %}
    
                            <div class="form row with-forms">
                                <!-- Home Type -->
                                <div class="col-md-6">
                                    {{ form.home_type.label_tag }}
                                    {% render_field form.home_type class="chosen-select-no-single" %}
                                    {{ form.home_type.errors }}
                                    <small class="help-text text-muted">{{ form.home_type.help_text }}</small>
                                </div>
    
                                <!-- Interior -->
                                <div class="col-md-6">
                                    {{ form.interior.label_tag }}
                                    {% render_field form.interior class="chosen-select-no-single" %}
                                    {{ form.interior.errors }}
                                    <small class="help-text text-muted">{{ form.interior.help_text }}</small>
                                </div>
                            </div>
    
                            <div class="form row with-forms">
                                <!-- Rooms -->
                                <div class="col-md-6">
                                    {{ form.rooms.label_tag }}
                                    {{ form.rooms }}
                                    {{ form.rooms.errors }}
                                    <small class="help-text text-muted">{{ form.rooms.help_text }}</small>
                                </div>
    
                                <!-- Bedrooms -->
                                <div class="col-md-6">
                                    {{ form.bedrooms.label_tag }}
                                    {{ form.bedrooms }}
                                    {{ form.bedrooms.errors }}
                                    <small class="help-text text-muted">{{ form.bedrooms.help_text }}</small>
                                </div>
                            </div>
                        </div>
    
                        <p><i>More options to be added soon!</i></p>
    
                        <button class="button margin-top-10" type="submit" {% if reached_max_sp %} disabled {% endif %}>Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}