api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views import UserViewSet, ListingReportViewSet, CommentReportViewSet, ListingViewSet, PlaceViewSet

api_router = DefaultRouter()
api_router.register('users', UserViewSet, 'user')
api_router.register('listingreports', ListingReportViewSet, 'listingreport')
api_router.register('commentreports', CommentReportViewSet, 'commentreport')
api_router.register('listings', ListingViewSet, 'listing')
api_router.register('places', PlaceViewSet, 'place')


urlpatterns = [
    path('', include(api_router.urls)),
    path('admin/', include('rest_framework.urls')),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

authy/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView
from django.utils.translation import gettext_lazy as _

from authy import views


urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('register/', views.RegisterView.as_view(), name='register'),

    path('register/complete/', TemplateView.as_view(
        template_name='registration/register_complete.html',
        extra_context={'title': _('Registration complete')},
    ), name='register_complete'),

    path('register/closed/', TemplateView.as_view(
        template_name='registration/register_closed.html',
        extra_context={'title': _('Registration closed')},
    ), name='register_closed'),

    path('pw/change/', views.PasswordChangeView.as_view(), name='password_change'),

    path('pw/change-done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('pw/reset/', views.PasswordResetView.as_view(), name='password_reset'),

    path('pw/reset-done/', TemplateView.as_view(
        template_name ='registration/password_reset_done.html',
        extra_context={'title': _('Password reset initiated')},
    ), name='password_reset_done'),

    path('pw/reset-complete/', TemplateView.as_view(
        template_name='registration/password_reset_complete.html',
        extra_context={'title': _("Password reset completed")},
    ), name='password_reset_complete'),

    re_path(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
            views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

listings/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('search/', views.ListingSearchView.as_view(), name='search'),
    path('create/', views.ListingCreateView.as_view(), name='create'),
    path('compare/', views.ListingCompareView.as_view(), name='compare'),
    path('get_json_data/', views.ListingJsonData.as_view(), name='get_json'),

    # Slug related urls
    path('<slug:slug>/', views.ListingDetailView.as_view(), name='detail'),  # Remove the last slash if Django complains
    path('<slug:slug>/update/', views.ListingUpdateView.as_view(), name='update'),
    path('<slug:slug>/delete/', views.ListingDeleteView.as_view(), name='delete'),
    path('<slug:slug>/toggle_status/', views.ListingToggleStatusView.as_view(), name='update_status'),
]

najdistandjango30/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from listings.views import ListingIndexView

from authy.views import LoginView


urlpatterns = [
    path('',            ListingIndexView.as_view(), name='index'),
    path('listings/',   include(('listings.urls', 'listings'), namespace='listings')),
    path('accounts/',   include('registration.backends.default.urls')),  # Used only for the Activation part
    path('user/',       include(('users.urls', 'users'), namespace='accounts')),
    path('auth/',       include(('authy.urls', 'authy'), namespace='authy')),
    path('sp/',         include(('searchprofiles.urls', 'searchprofiles'), namespace='searchprofiles')),
    path('office/',     admin.site.urls),

    # Hack alert, this is needed for the ?next issue when changing the 'auth_login'..
    path('login/',      LoginView.as_view(), name='auth_login'),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
] + urlpatterns
#
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

searchprofiles/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('manage/',             views.search_profile_manage,    name='manage'),
    path('create/',             views.search_profile_create,    name='create'),
    path('toggle/',             views.search_profile_toggle,    name='toggle'),
    path('update/<int:pk>/',    views.search_profile_update,    name='update'),
    path('delete/<int:pk>/',    views.search_profile_delete,    name='delete'),
]

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('properties/', views.properties, name='properties'),
    path('bookmarks/', views.bookmarks, name='bookmarks'),
    path('deactivate/', views.deactivate_account, name='deactivate'),
    path('profile/update/', views.update, name='profile_update'),
    path('publisher/<slug:identifier>/', views.publisher, name='publisher'),
]

templates/_shared/breadcrumbs.html
<div id="titlebar">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>{{ title }}</h2>
                <!-- Breadcrumbs -->
                <nav id="breadcrumbs">
                     <ul>
                         {% for crumb, link in crumbs.items %}
                            <li><a href="{{ link }}">{{ crumb }}</a></li>
                         {% endfor %}
                     </ul>
                </nav>
            </div>
        </div>
    </div>
</div>

templates/_shared/footer.html
{% load static %}
<div id="footer" class="sticky-footer">
	<!-- Main -->
	<div class="container">
		<div class="row">
			<div class="col-md-5 col-sm-6">
				<img class="footer-logo" src="{% static 'assets/images/logo.png' %}" alt="">
				<br><br>
				<p>Morbi convallis bibendum urna ut viverra. Maecenas quis consequat libero, a feugiat eros. Nunc ut lacinia tortor morbi ultricies laoreet ullamcorper phasellus semper.</p>
			</div>

			<div class="col-md-4 col-sm-6 ">
				<h4>Helpful Links</h4>
				<ul class="footer-links">
					<li><a href="{% url 'authy:login' %}">Login</a></li>
					<li><a href="{% url 'authy:register' %}">Sign Up</a></li>
					<li><a href="{% url 'accounts:profile' %}">My Profile</a></li>
					<li><a href="{% url 'listings:create' %}">Add Property</a></li>
					<li><a href="#">Compare Properties</a></li>
					<li><a href="#">Premium Account</a></li>
				</ul>

				<ul class="footer-links">
					<li><a href="#">FAQ</a></li>
					<li><a href="#">Blog</a></li>
					<li><a href="#">Our Agents</a></li>
					<li><a href="#">How It Works</a></li>
                    <li><a href="#">Privacy Policy</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
				<div class="clearfix"></div>
			</div>		

			<div class="col-md-3  col-sm-12">
				<h4>Contact Us</h4>
				<div class="text-widget">
					<span>12345 Little Lonsdale St, Melbourne</span> <br>
					Phone: <span>(123) 123-456 </span><br>
					E-Mail:<span> <a href="#">office@example.com</a> </span><br>
				</div>

				<ul class="social-icons margin-top-20">
					<li><a class="facebook" href="#"><i class="icon-facebook"></i></a></li>
					<li><a class="twitter" href="#"><i class="icon-twitter"></i></a></li>
					<li><a class="gplus" href="#"><i class="icon-gplus"></i></a></li>
					<li><a class="vimeo" href="#"><i class="icon-vimeo"></i></a></li>
				</ul>

			</div>

		</div>
		
		<!-- Copyright -->
		<div class="row">
			<div class="col-md-12">
				<div class="copyrights">© 2020 Findeo. All Rights Reserved.</div>
			</div>
		</div>

	</div>

</div>

templates/_shared/header.html
{% load static %}
<header id="header-container" class="header-style-3">

	<!-- Header -->
	<div id="header">
		<div class="container">
			
			<!-- Left Side Content -->
			<div class="left-side">
				
				<!-- Logo -->
				<div id="logo">
					<a href="{% url 'index' %}"><img src="{% static 'assets/images/logo2.png' %}" alt=""></a>
				</div>


				<!-- Mobile Navigation -->
				<!-- <div class="mmenu-trigger">
					<button class="hamburger hamburger--collapse" type="button">
						<span class="hamburger-box">
							<span class="hamburger-inner"></span>
						</span>
					</button>
				</div> -->


				<!-- Main Navigation -->
{#				<nav id="navigation" class="style-3">#}
{#					<ul id="responsive">#}
{##}
{#						<li><a href="#">Home</a>#}
{#							<ul>#}
{#								<li><a href="#">Home 1</a></li>#}
{#								<li><a href="#">Home 2</a></li>#}
{#								<li><a href="#">Home 3</a></li>#}
{#								<li><a href="#">Home 4</a></li>#}
{#							</ul>#}
{#						</li>#}
{##}
{#						<li><a href="#">Listings</a>#}
{#						<li><a class="current" href="#">Listings</a>#}
{#							<ul>#}
{#								<li><a href="#">List Layout</a>#}
{#									<ul>#}
{#										<li><a href="#">With Sidebar</a></li>#}
{#										<li><a href="#">With Map</a></li>#}
{#										<li><a href="#">Full Width</a></li>#}
{#									</ul>#}
{#								</li>#}
{#								<li><a href="#">Grid Layout</a>#}
{#									<ul>#}
{#										<li><a href="#">Standard With Sidebar</a></li>#}
{#										<li><a href="#">Compact With Sidebar</a></li>#}
{#										<li><a href="#">With Map</a></li>#}
{#										<li><a href="#">Full Width</a></li>#}
{#									</ul>#}
{#								</li>#}
{#								<li><a href="#">Half Map</a>#}
{#									<ul>#}
{#										<li><a href="#">List Layout</a></li>#}
{#										<li><a href="#">Grid Standard Layout</a></li>#}
{#										<li><a href="#">Grid Compact Layout</a></li>#}
{#									</ul>#}
{#								</li>#}
{#							</ul>#}
{#						</li>#}
{##}
{#						<li><a href="#">Features</a>#}
{#							<ul>#}
{#								<li><a href="#">Single Properties</a>#}
{#									<ul>#}
{#										<li><a href="#">Property Style 1</a></li>#}
{#										<li><a href="#">Property Style 2</a></li>#}
{#										<li><a href="#">Property Style 3</a></li>#}
{#									</ul>#}
{#								</li>#}
{#								<li><a href="#">Search Styles</a>#}
{#									<ul>#}
{#										<li><a href="#">Home Search 1</a></li>#}
{#										<li><a href="#">Home Search 2</a></li>#}
{#										<li><a href="#">Home Search 3</a></li>#}
{#										<li><a href="#">Advanced Style</a></li>#}
{#										<li><a href="#">Sidebar Search</a></li>#}
{#									</ul>#}
{#								</li>#}
{#								<li><a href="#">My Account</a>#}
{#									<ul>#}
{#										<li><a href="#">My Profile</a></li>#}
{#										<li><a href="#">Bookmarked Listings</a></li>#}
{#										<li><a href="#">My Properties</a></li>#}
{#										<li><a href="#">Change Password</a></li>#}
{#									</ul>#}
{#								</li>#}
{#								<li><a href="#">Agencies & Agents</a>#}
{#									<ul>#}
{#										<li><a href="#">Agencies List</a></li>#}
{#										<li><a href="#">Agency Page</a></li>#}
{#										<li><a href="#">Agents List</a></li>#}
{#										<li><a href="#">Agent Page</a></li>#}
{#									</ul>#}
{#								</li>#}
{##}
{#								<li><a href="#">Compare Properties</a></li>#}
{#								<li><a href="#">Submit Property</a></li>#}
{#							</ul>#}
{#						</li>#}
{##}
{#						<li><a href="#">Pages</a>#}
{#							<ul>#}
{#								<li><a href="#">Blog</a>#}
{#									<ul>#}
{#										<li><a href="#">Blog</a></li>#}
{#										<li><a href="#">Blog Post</a></li>#}
{#									</ul>#}
{#								</li>#}
{#								<li><a href="#">Contact</a></li>#}
{#								<li><a href="#">Elements</a></li>#}
{#								<li><a href="#">Pricing Tables</a></li>#}
{#								<li><a href="#">Typography</a></li>#}
{#								<li><a href="#">Icons</a></li>#}
{#							</ul>#}
{#						</li>#}
{##}
{#					</ul>#}
{#				</nav>#}
				<div class="clearfix"></div>
				<!-- Main Navigation / End -->
				
			</div>
			<!-- Left Side Content / End -->
            
            <!-- Right Side Content / End -->
			<div class="right-side">
				<!-- Header Widget -->
				<div class="header-widget">

                    {% if request.user.is_authenticated %}
                    <!-- User Menu -->
                    <div class="user-menu">
                        <div class="user-name">
							<span>
								<img src="{{ user.get_profile_image }}" alt="user avatar" />
							</span>
							<p class="user-name-text">Hi, {{ request.user }}</p>
						</div>
                        <ul>
                            <li><a href="{% url 'accounts:profile' %}"><i class="sl sl-icon-user"></i> My Profile</a></li>
                            <!-- <li><a href="my-bookmarks.html"><i class="sl sl-icon-star"></i> Bookmarks</a></li> -->
                            <li><a href="{% url 'accounts:properties' %}"><i class="sl sl-icon-docs"></i> My Properties</a></li>
                            <li><a href="{% url 'searchprofiles:manage' %}"><i class="sl sl-icon-notebook"></i> Search Profiles</a></li>
                            {% if request.user.is_superuser %}
                                <li><a href="{% url 'admin:index' %}"><i class="sl sl-icon-star"></i> Admin Office</a></li>
                            {% endif %}
                            <li><a href="{% url 'authy:logout' %}"><i class="sl sl-icon-logout"></i> Log Out</a></li>
                        </ul>
                    </div>
                    {% else %}
                    <a href="{% url 'authy:register' %}" class="sign-in"><i class="sl sl-icon-user-follow"></i> Register</a>
                    <a href="{% url 'authy:login' %}" class="sign-in"><i class="sl sl-icon-login"></i> Login</a>
                    {% endif %}

					<a href="{% url 'listings:create' %}" class="button border white"><i class="sl sl-icon-plus"></i><span> New Listing</span></a>
				</div>
				<!-- Header Widget / End -->
			</div>
			<!-- Right Side Content / End -->

		</div>
	</div>
	<!-- Header / End -->

</header>
<div class="clearfix"></div>

templates/_shared/profile-sidemenu.html
<div class="my-account-nav-container">

    <ul class="my-account-nav">
        <li class="sub-nav-title">Manage Account</li>
        <li>
            <a href="{% url 'accounts:profile' %}"
                {% url 'accounts:profile' as current_url%}
                {% if request.path == current_url %} class="current"{% endif %}>
                <i class="sl sl-icon-user"></i> My Profile
            </a>
        </li>
        <li>
            <a href="{% url 'accounts:properties' %}"
                {% url 'accounts:properties' as current_url%}
                {% if request.path == current_url %} class="current"{% endif %}>
                <i class="sl sl-icon-docs"></i> My Properties
            </a>
        </li>
        <li>
            <a href="{% url 'listings:create' %}"
                {% url 'listings:create' as current_url%}
                {% if request.path == current_url %} class="current"{% endif %}>
                <i class="sl sl-icon-action-redo"></i> Submit New Property
            </a>
        </li>
        <li>
            <a href="{% url 'accounts:bookmarks' %}"
                {% url 'accounts:bookmarks' as current_url%}
                {% if request.path == current_url %} class="current"{% endif %}>
                <i class="sl sl-icon-star"></i> Bookmarked Properties
            </a>
        </li>
    </ul>

    <ul class="my-account-nav">
        <li class="sub-nav-title">Search Profiles</li>
        <li>
            <a href="{% url 'searchprofiles:create' %}"
                {% url 'searchprofiles:create' as current_url%}
                {% if request.path == current_url %} class="current"{% endif %}>
                <i class="sl sl-icon-plus"></i>Create SP
            </a>
        </li>
        <li>
            <a href="{% url 'searchprofiles:manage' %}"
                {% url 'searchprofiles:manage' as current_url%}
                {% if request.path == current_url %} class="current"{% endif %}>
                <i class="sl sl-icon-notebook"></i>Manage SP
            </a>
        </li>
    </ul>

    <ul class="my-account-nav">
        <li class="sub-nav-title">Settings</li>
        <li>
            <a href="{% url 'accounts:profile_update' %}"
                {% url 'accounts:profile_update' as current_url %}
                {% if request.path == current_url %} class="current"{% endif %}>
                <i class="sl sl-icon-user-following"></i> Update Profile
            </a>
        </li>
        <li>
            <a href="{% url 'authy:password_change' %}"
                {% url 'authy:password_change' as current_url %}
                {% if request.path == current_url %} class="current"{% endif %}>
                <i class="sl sl-icon-lock"></i> Change Password
            </a>
        </li>
        <li>
            <a href="{% url 'accounts:deactivate' %}"
            {% url 'accounts:deactivate' as current_url %}
            {% if request.path == current_url %} class="current"{% endif %}>
            <i class="sl sl-icon-trash"></i> Deactivate Account
            </a>
        </li>
        <li><a href="{% url 'authy:logout' %}"><i class="sl sl-icon-logout"></i> Log Out</a></li>
    </ul>

</div>

templates/_shared/title.html
{% if title %}
    <title>{{ title }} | {{ project_name }}</title>
{% else %}
    <title>{{ project_name }}</title>
{% endif %}