api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views import UserViewSet, ListingReportViewSet, CommentReportViewSet, ListingViewSet, PlaceViewSet

api_router = DefaultRouter()
api_router.register('users', UserViewSet, 'user')
api_router.register('listingreports', ListingReportViewSet, 'listingreport')
api_router.register('commentreports', CommentReportViewSet, 'commentreport')
api_router.register('listings', ListingViewSet, 'listing')
api_router.register('places', PlaceViewSet, 'place')


urlpatterns = [
    path('', include(api_router.urls)),
    path('admin/', include('rest_framework.urls')),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

listings/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('search/', views.ListingSearchView.as_view(), name='search'),
    path('create/', views.ListingCreateView.as_view(), name='create'),
    path('compare/', views.ListingCompareView.as_view(), name='compare'),
    path('get_json_data/', views.ListingJsonData.as_view(), name='get_json'),

    # Slug related urls
    path('<slug:slug>/', views.ListingDetailView.as_view(), name='detail'),  # Remove the last slash if Django complains
    path('<slug:slug>/update/', views.ListingUpdateView.as_view(), name='update'),
    path('<slug:slug>/delete/', views.ListingDeleteView.as_view(), name='delete'),
    path('<slug:slug>/toggle_status/', views.ListingToggleStatusView.as_view(), name='update_status'),
]

najdistandjango30/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from listings.views import ListingIndexView

from authy.views import LoginView


urlpatterns = [
    path('',            ListingIndexView.as_view(), name='index'),
    path('listings/',   include(('listings.urls', 'listings'), namespace='listings')),
    path('accounts/',   include('registration.backends.default.urls')),  # Used only for the Activation part
    path('user/',       include(('users.urls', 'users'), namespace='accounts')),
    path('auth/',       include(('authy.urls', 'authy'), namespace='authy')),
    path('sp/',         include(('searchprofiles.urls', 'searchprofiles'), namespace='searchprofiles')),
    path('office/',     admin.site.urls),

    # Hack alert, this is needed for the ?next issue when changing the 'auth_login'..
    path('login/',      LoginView.as_view(), name='auth_login'),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
] + urlpatterns
#
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

searchprofiles/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('manage/',             views.search_profile_manage,    name='manage'),
    path('create/',             views.search_profile_create,    name='create'),
    path('toggle/',             views.search_profile_toggle,    name='toggle'),
    path('update/<int:pk>/',    views.search_profile_update,    name='update'),
    path('delete/<int:pk>/',    views.search_profile_delete,    name='delete'),
]

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('properties/', views.properties, name='properties'),
    path('bookmarks/', views.bookmarks, name='bookmarks'),
    path('deactivate/', views.deactivate_account, name='deactivate'),
    path('profile/update/', views.update, name='profile_update'),
    path('publisher/<slug:identifier>/', views.publisher, name='publisher'),
]

users/models.py
import hashlib
import uuid

from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator, MinLengthValidator
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from configdata import REGEX_TELEPHONE_VALIDATOR
from .managers import CustomUserManager
from .utils import profile_image_directory_path


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class User(AbstractUser, BaseModel):
    """
    A base class that represents an instance of a logged-in User
    """
    first_name = models.CharField(max_length=255, blank=False, validators=[MinLengthValidator(2)])
    last_name = models.CharField(max_length=255, blank=False, validators=[MinLengthValidator(2)])
    email = models.EmailField(unique=True, blank=False)
    telephone = models.CharField(_('Phone number'), max_length=255,
                                 validators=[RegexValidator(REGEX_TELEPHONE_VALIDATOR,
                                 message="Phone number should be a combination of numbers and '+' sign (i.e. +31612341234 or 0612341234)")])
    username = None
    profile_image = models.ImageField(upload_to=profile_image_directory_path, blank=True, null=True)
    identifier = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    soft_delete = models.BooleanField(null=True, default=False)

    def __str__(self):
        return self.get_full_name()

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    @property
    def avatar(self):
        base_url = 'https://www.gravatar.com/avatar/'
        gravatar_url = base_url + hashlib.md5(self.email.lower().encode('utf-8')).hexdigest() + '?d=wavatar&s=100'
        return gravatar_url

    @property
    def get_profile_image(self):
        if self.profile_image:
            return self.profile_image.url
        return self.avatar

    def get_short_name(self):
        return f"{self.first_name} {self.last_name[:1]}."

    def has_listings(self):
        return self.listings.exists()

    # TODO: Check queries here!
    def get_listings(self):
        return self.listings.prefetch_related('city').all()

    def get_absolute_url(self):
        return reverse('accounts:publisher', kwargs={'identifier': self.identifier})

    @property
    def is_premium_user(self):
        return self.is_staff  # TODO: To be replaced with real logic about being Premium user

    def has_search_profiles(self):
        return self.searchprofiles.exists()

    def get_search_profiles(self):
        return self.searchprofiles.prefetch_related('city').all().order_by('-created_at')

    # TODO: Rename this one!
    def has_reached_max_number_of_sp(self):
        return not self.is_premium_user and self.searchprofiles.all().count() >= 1

    def get_bookmarks(self):
        return self.bookmarks.all()

    def _deactivate_account(self):
        self.is_active = False
        self.soft_delete = True

    def _deactivate_listings(self):
        self.get_listings().update(is_available=False)

    def _deactivate_search_profiles(self):
        self.get_search_profiles().update(is_active=False)

    def deactivate(self):
        self._deactivate_account()
        self._deactivate_listings()
        self._deactivate_search_profiles()
        self.save()


class Bookmarks(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bookmarks')
    listing = models.ForeignKey('listings.Listing', on_delete=models.CASCADE, related_name='bookmarked_by')

    class Meta:
        verbose_name_plural = 'Bookmarks'

    def __str__(self):
        return f"{self.user} - {self.listing}"

    def clean(self):
        if self.user_id == self.listing.user_id:
            raise ValidationError("You can't bookmark your own listing!")

users/forms.py
from django import forms

from .models import User


class UserUpdateForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, help_text="You need to enter your current password to make changes", )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'telephone', 'email', 'profile_image', )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def clean_password(self):
        user = self.instance
        entered_password = self.cleaned_data['password']
        if not user.check_password(entered_password):
            raise forms.ValidationError("Incorrect password!")
        return entered_password

searchprofiles/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods

from configdata import FORBIDDEN_MESAGE
from listings.decorators import ajax_required
from .forms import UserSearchProfileForm
from .models import SearchProfiles


@login_required()
def search_profile_manage(request):
    context = {'title': "Manage Search Profiles"}
    context.update({'reached_max_sp': request.user.has_reached_max_number_of_sp(),
                    'search_profiles': request.user.get_search_profiles(),
                    'active_sp': request.user.get_search_profiles().count_active(),
                    'crumbs': {
                        "Home": reverse('index'),
                        "Account": reverse('accounts:profile'),
                        "Search Profile": '#',
                    }
                    })
    return render(request, 'searchprofile/manage.html', context)


@login_required()
def search_profile_create(request):
    context = {
        'title': "Create Search Profile",
        'crumbs': {
           "Home": reverse('index'),
           "Account": reverse('accounts:profile'),
           "Search Profile": reverse('searchprofiles:manage'),
           "Create": "#"
        }
    }

    if request.method == 'POST':
        form = UserSearchProfileForm(request.POST, user=request.user)
        context.update({'form': form})
        if form.is_valid():
            sp = form.save(commit=False)
            sp.user = request.user
            sp.save()
            messages.success(request, _("Search Profile added!"))
            return redirect(reverse('searchprofiles:manage'))
        else:
            return render(request, 'searchprofile/create.html', context)

    form = UserSearchProfileForm(user=request.user)

    context.update({'form': form, 'reached_max_sp': request.user.has_reached_max_number_of_sp()})
    return render(request, 'searchprofile/create.html', context)


@login_required()
def search_profile_delete(request, pk):
    search_profile = get_object_or_404(SearchProfiles, pk=pk)
    if search_profile.user != request.user:
        return HttpResponseForbidden(_(FORBIDDEN_MESAGE))
    search_profile.delete()
    messages.info(request, _("Search Profile deleted."))
    return redirect(reverse('searchprofiles:manage'))


@login_required()
def search_profile_update(request, pk):
    search_profile = get_object_or_404(SearchProfiles, pk=pk)
    if search_profile.user != request.user:
        return HttpResponseForbidden(_(FORBIDDEN_MESAGE))

    context = {
        'title': _('Update Search Profile'),
        'crumbs': {
            "Home": reverse('index'),
            "Account": reverse('accounts:profile'),
            "Search Profile": reverse('searchprofiles:manage'),
            "Update": "#"
        }
    }

    if request.method == 'POST':
        form = UserSearchProfileForm(request.POST, instance=search_profile, user=request.user, update=True)
        context.update({'form': form})
        if form.is_valid():
            if form.has_changed():
                form.save()
                messages.info(request, _("Search Profile updated!"))
            return redirect(reverse('searchprofiles:manage'))
        else:
            return render(request, 'searchprofile/update.html', context)

    form = UserSearchProfileForm(user=request.user, instance=search_profile, update=True)
    context.update({'form': form})
    return render(request, 'searchprofile/update.html', context)


@ajax_required
@require_http_methods(['POST'])
@csrf_exempt
def search_profile_toggle(request):
    # Sanity checks
    ajax_user = getattr(request, 'user', None)
    if ajax_user.is_anonymous:
        return JsonResponse({'error': 'You need to be logged-in for this action'}, status=403)
    sp_key = request.POST.get('sp_pk', None)
    if not sp_key:
        return JsonResponse({'error': 'Requested key not found in POST.'}, status=403)
    try:
        search_profile = SearchProfiles.objects.get(pk=sp_key)
    except SearchProfiles.DoesNotExist:
        return JsonResponse({'error': 'Requested Search Profile not found.'}, status=404)
    if search_profile.user != ajax_user:
        return JsonResponse({'error': "You don't have permission to do this action."}, status=403)

    search_profile.is_active = not search_profile.is_active
    search_profile.save()
    return JsonResponse({'data': 'Search Profile successfully updated!'}, status=200)

users/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import UserUpdateForm
from .models import User
from .tasks import send_deactivation_email


@login_required
def profile(request):
    context = {
        'title': 'My Profile',
        'user': request.user,
        'listings': request.user.get_listings(),
        'search_profiles': request.user.get_search_profiles(),
        'crumbs': {
            "Home": reverse('index'),
            "Account": '#',
        }
    }
    return render(request, 'users/profile.html', context)


@login_required
def properties(request):
    user_listings = request.user.get_listings()
    context = {
        'title': 'My Properties',
        'active': user_listings.active(),
        'inactive': user_listings.inactive(),
        'pending': user_listings.pending(),
        'has_listings': request.user.has_listings(),
        'crumbs': {
            "Home": reverse('index'),
            "Account": reverse('accounts:profile'),
            "Properties": '#',
        }
    }
    return render(request, 'users/properties.html', context)


@login_required
def bookmarks(request):
    context = {
        'title': 'Bookmarked Properties',
        'bookmarks': request.user.get_bookmarks(),
        'crumbs': {
            "Home": reverse('index'),
            "Account": reverse('accounts:profile'),
            "Bookmarked": '#',
        }
    }
    return render(request, 'users/bookmarks.html', context)


@login_required
def update(request):
    context = {'title': 'Update Profile',
               'crumbs': {
                   "Home": reverse('index'),
                   "Account": reverse('accounts:profile'),
                   "Update": "#"
               }
           }

    if request.method == 'POST':
        form = UserUpdateForm(request.POST, request.FILES, instance=request.user)
        context.update({'form': form})
        if form.changed_data and form.is_valid():
            form.save()
            messages.info(request, "Account updated successfully!")
        else:
            return render(request, 'users/update.html', context)
        return redirect(reverse('accounts:profile'))
    form = UserUpdateForm(instance=request.user)
    context.update({'form': form})
    return render(request, 'users/update.html', context)


def publisher(request, identifier):
    try:
        user = User.objects.prefetch_related('listings__city').get(identifier=identifier)
    except User.DoesNotExist:
        raise Http404("User does not exist.")
    if user == request.user:
        messages.info(request, "You have been redirected to your own profile.")
        return redirect(reverse('accounts:profile'))

    context = {
        'title': 'Publisher',
        'publisher': user,
        'listings': user.get_listings(),
        'crumbs': {
            "Home": reverse('index'),
            "Publisher": '#',
        }

    }
    return render(request, 'users/publisher.html', context)


@login_required
def deactivate_account(request):
    context = {
        'title': 'Deactivate Account',
           'crumbs': {
               "Home": reverse('index'),
               "Account": reverse('accounts:profile'),
               "Deactivate": "#"
           }
       }
    if request.method == 'POST':
        request.user.deactivate()
        send_deactivation_email.delay(request.user.pk)
        logout(request)
        messages.info(request, "Your account has been disabled! We are sorry to see you go.")
        return redirect(reverse('index'))
    return render(request, 'users/deactivate.html', context)

templates/users/bookmarks.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %}
    {% include '_shared/title.html' %}
{% endblock %}

{% block content %}
    {% include '_shared/breadcrumbs.html' %}

    <div class="container padding-bottom-70">
        <div class="row">

            <!-- Widget -->
            <div class="col-md-4">
                <div class="sidebar left">
                    {% include '_shared/profile-sidemenu.html' %}
                </div>
            </div>

            <div class="col-md-8 padding-bottom-70">
                <div class="main-content">
                    <i>This functionality is <b>Under Development!</b></i>
    
    {#                {% if bookmarks %}#}
    {#                    <table class="manage-table responsive-table">#}
    {#                        <tr>#}
    {#                            <th><i class="fa fa-file-text"></i> Property</th>#}
    {#                            <th><i class="fa fa-file-text"></i> Actions</th>#}
    {#                        </tr>#}
    {#                        {% for bookmark in bookmarks %}#}
    {#                            <tr>#}
    {#                                <td class="title-container">#}
    {#                                    <img src="{{ bookmark.listing.get_cover_image.url }}"#}
    {#                                         alt="{{ bookmark.listing.title }}">#}
    {#                                    <div class="title">#}
    {#                                        <h4>#}
    {#                                            <a href="{% url 'listings:detail' bookmark.listing.slug %}">{{ bookmark.listing.title|truncatewords:8 }}</a>#}
    {#                                        </h4>#}
    {#                                        <span>{{ bookmark.listing.zip_code }}, {{ bookmark.listing.city }} </span>#}
    {#                                        <span class="table-property-price">{{ bookmark.listing.price }} <i>&euro;</i></span>#}
    {#                                    </div>#}
    {#                                </td>#}
    {#                                <td class="action">#}
    {#                                    <a href="{% url 'listings:update' bookmark.listing.slug %}"><i#}
    {#                                            class="fa fa-star-o"></i> Remove Bookmark</a>#}
    {#                                    <a href="{% url 'listings:update' bookmark.listing.slug %}"><i#}
    {#                                            class="fa fa-star-o"></i> Contact Owner</a>#}
    {#                                </td>#}
    {#                            </tr>#}
    {#                        {% endfor %}#}
    {#                    </table>#}
    {#                {% else %}#}
    {#                    <p>You don't have any bookmarked properties.</p>#}
    {#                {% endif %}#}
                </div>

            </div>
        </div>
    </div>
{% endblock %}

templates/users/group_properties.html
{% load humanize %}

{% if listings %}
    <table class="manage-table responsive-table">
        <tr>
            <th><i class="fa fa-file-text"></i> Property</th>
            <th class="expire-date"><i class="fa fa-calendar"></i> Creation Date</th>
            <th><i class="fa fa-file-text"></i> Actions</th>
        </tr>
        {% for object in listings %}
                <tr>
                    <td class="title-container">
                        <img src="{{ object.get_cover_image.url }}" alt="{{ object.title }}">
                        <div class="title">
                            <h4><a href="{% url 'listings:detail' object.slug %}">{{ object.title|truncatewords:8 }}</a></h4>
                            <span>{{ object.zip_code }}, {{ object.city }} </span>
                            <span class="table-property-price">{{ object.price }} <i>&euro;</i></span>
                        </div>
                    </td>
                    <td class="expire-date">{{ object.created_at|naturalday }}</td>
                    <td class="action">
                        <a href="{% url 'listings:update' object.slug %}"><i class="fa fa-pencil"></i> Update</a>
                        <a href="{% url 'listings:update_status' object.slug %}"
                           onclick="return confirm('Are you sure you want to change this property availability status?');">
                            {% if action %}<i class="fa  fa-eye-slash"></i>{{ action }}{% endif %}
                        </a>
                        <a href="{% url 'listings:delete' object.slug %}" class="delete"
                           onclick="return confirm('Are you sure you want to delete this listing?');">
                            <i class="fa fa-remove"></i> Delete
                        </a>
                    </td>
                </tr>

        {% endfor %}
    </table>
    <a href="{% url 'listings:create' %}" class="margin-top-40 button">Submit New Property</a>
{% else %}
    {% if not has_listings %}
        <p>You don't have any listings. Would you like to <a class="margin-top-40 button" href="{% url 'listings:create' %}">create one?</a></p>
    {% endif %}
{% endif %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %}
    {% include '_shared/title.html' %}
{% endblock %}

{% block content %}
    {% include '_shared/breadcrumbs.html' %}

    <div class="container padding-bottom-70">
        <div class="row">
            <!-- Widget -->
            <div class="col-md-4">
                <div class="sidebar left">
                    {% include '_shared/profile-sidemenu.html' %}
                </div>
            </div>

            <div class="col-md-8 padding-bottom-70">
                <div class="main-content">
                    {% with request.user as user %}
                    <div class="row profile-header">
                        <div class="col-sm-8 col-xs-12">
                            <h3 class="desc-headline no-border margin-top-45">Profile details</h3>
                            <p class="profile-header-login"><span>Last login:</span> {{ user.last_login }}</p>
                        </div>
                        <div class="col-sm-4 col-xs-12">
                            <div class="profile-header-photo">
                                <img src="{{ user.get_profile_image }}" alt="user profile image">
                            </div>
                        </div>
                    </div>
                    <div class="profile-body">

                        <div class="row">
                            <div class="col-sm-3 col-xs-12">
                                <label>Full name:</label>
                            </div>
                            <div class="col-sm-9 col-xs-12">
                                <p>{{ user.get_full_name }}</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-3 col-xs-12">
                                <label>Email:</label>
                            </div>
                            <div class="col-sm-9 col-xs-12">
                                <p>{{ user.email }}</p>
                            </div>
                        </div>
                         
                        <div class="row">
                            <div class="col-sm-3 col-xs-12">
                                <label>Phone:</label>
                            </div>
                            <div class="col-sm-9 col-xs-12">
                                <p>{{ user.telephone }}</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-3 col-xs-12">
                                <label>Submitted properties:</label>
                            </div>
                            <div class="col-sm-9 col-xs-12">
                                {% if user.has_listings %}
                                    <p><a href="{% url 'accounts:properties' %}">You have a total of 4 (2 active) properties</a></p>
                                {% else %}
                                    <p>No properties submitted so far... Well? What are you waiting for?</p>
                                {% endif %}
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-sm-3 col-xs-12">
                                <label>Search profiles:</label>
                            </div>
                            <div class="col-sm-9 col-xs-12">
                                {% if user.is_premium_user %}
                                    <div class="premium-cta">            
                                        <p>This feature is only available for premium users</p>
                                        <a class="button" href="#">Go Premium Today!</a>
                                    </div>
                                {% else %}
                                    <p><a href="{% url 'searchprofiles:manage' %}">4 active search profiles</a></p>
                                {% endif %}
                            </div>
                        </div>
                        
                    </div>
                    {% endwith %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/users/update.html
{% extends 'base.html' %}

{% block title %}
    {% include '_shared/title.html' %}
{% endblock %}

{% block content %}
{% include '_shared/breadcrumbs.html' %}

<div class="container padding-bottom-70">
	<div class="row">

        <!-- Widget -->
		<div class="col-md-4">
			<div class="sidebar left">
				{% include '_shared/profile-sidemenu.html' %}
			</div>
        </div>
        
        <div class="col-md-8 padding-bottom-70">
            <div class="main-content">
                <form method="post" enctype="multipart/form-data" autocomplete="off">
                    {% csrf_token %}
    
                    {% for hidden_field in form.hidden_fields %}
                        {{ hidden_field }}
                    {% endfor %}
    
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                        {% for error in form.non_field_errors %}
                            {{ error }}
                        {% endfor %}
                        </div>
                    {% endif %}
    
                    <div class="col-md-8 my-profile">
                        <div class="form-group form-row">
                            <label class="control-label" for="{{ form.first_name.id_for_label }}">
                                {{ form.first_name.label }}:
                                <i class="im im-icon-Font-Name"></i>
                                {{ form.first_name }}
                            </label>
                            {{ form.first_name.errors }}
                            <small class="help-text text-muted">{{ form.first_name.help_text }}</small>
                        </div>
    
                        <div class="form-group form-row">
                            <label class="control-label" for="{{ form.last_name.id_for_label }}">
                                {{ form.last_name.label }}:
                                <i class="im im-icon-Font-Name"></i>
                                {{ form.last_name }}
                            </label>
                            {{ form.last_name.errors }}
                            <small class="help-text text-muted">{{ form.last_name.help_text }}</small>
                        </div>
    
                        <div class="form-group form-row">
                            <label class="control-label" for="{{ form.telephone.id_for_label }}">
                                {{ form.telephone.label }}:
                                <i class="im im-icon-Phone-2"></i>
                                {{ form.telephone }}
                            </label>
                            {{ form.telephone.errors }}
                            <small class="help-text text-muted">{{ form.telephone.help_text }}</small>
                        </div>
    
                        <div class="form-group form-row">
                            <label class="control-label" for="{{ form.email.id_for_label }}">
                                {{ form.email.label }}:
                                <i class="im im-icon-Mail"></i>
                                {{ form.email }}
                            </label>
                            {{ form.email.errors }}
                            <small class="help-text text-muted">{{ form.email.help_text }}</small>
                        </div>
    
                        <div class="form-group form-row">
                            <label class="control-label" for="{{ form.password.id_for_label }}">
                                {{ form.password.label }}:
                                <i class="im im-icon-Lock-2"></i>
                                {{ form.password }}
                            </label>
                            {{ form.password.errors }}
                            <small class="help-text text-muted">{{ form.password.help_text }}</small>
                        </div>
                        
                        <button type="submit" class="button margin-top-20 margin-bottom-20">Save Changes</button>
                    </div>
    
                    <div class="col-md-4">
                        <!-- Avatar -->
                        <div class="edit-profile-photo">
                            <img src="{{ request.user.get_profile_image }}" alt="user profile image">
                            <div class="change-photo-btn">
                                <div class="photoUpload">
                                    <span><i class="fa fa-upload"></i> Change Photo</span>
                                    <input type="file" name="profile_image" accept="image/*" id="id_profile_image" class="upload" />
                                </div>
                            </div>
                        </div>
    
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}